---

- name: download stone tarball
  sudo: yes
  get_url: >
    url={{ stone_url }}/{{ stone_version }}.tar.gz
    dest=/usr/local/src

- unarchive: src=/usr/local/src/{{ stone_version }}.tar.gz dest=/usr/local/src copy=no
- replace: dest=/usr/local/src/stone-2.3d-2.3.2.7/Makefile regexp='DUSE_EPOLL' replace='DUSE_EPOLL -D_GNU_SOURCE'
- command: make linux-ssl chdir=/usr/local/src/stone-2.3d-2.3.2.7
- command: cp stone /usr/local/bin chdir=/usr/local/src/stone-2.3d-2.3.2.7
